name: Render Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Regenerate people.json
        run: |
          jq . -s people/* > docs/people.json

      - name: Commit updated people.json
        uses: EndBug/add-and-commit@v7
        with:
          add: docs/people.json
          author_name: BuggieBot
          author_email: buggiebot@serenityos.org
          message: 'Update people.json'
